name = "alt:V Server"
description = "alt:V Sample Server"
gamemode = "Freeroam"
website = "example.ru"
language = "ru"

port = 7788
players = 128

debug = true
# password = "ultra-password"

announce = false
# token = 'YOUR_TOKEN'

modules = [ "js-module" ]
resources = [ "*" ]
